### ISSUE TITLE
使用Vue-cli3如何改造呢？

### ISSUE THREAD

**Issue by leaper1** [seizeDev/vue-koa2#2]
使用Vue-cli3脚手架搭建的项目，如何引入koa2？另外，vue项目原本就是使用axios和后端交互，那增加koa做请求转发的作用在哪里？

**Comment by seizeDev** [comment]
vue-cli3 本质上只是把webpack 的配置封装起来了，跟vue 版本和其他插件的版本没有什么关系，不用vue-cli3 就可以了。koa2加进去后可以作为中间层，比如某些接口可以前端自己实现，还有后续的接口返回可以在koa2  层处理数据。后端可以只做数据层，前端增加接口校验之类的
